Repository AY2021S2-CS2103-W17-2/tp, pull requests merged in 2021-03, with the labels that each got.

#48 Add-Appointment-Command: Command, Parser Classes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UserInputParser.java
  src/main/java/seedu/address/model/appointment/Timeslot.java
  src/main/java/seedu/address/storage/JsonAdaptedTimeslot.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UserInputParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement, type.Task

#50 Documentation for edit appt command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#49 Edit Appointment Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/UserInputParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UserInputParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#54 List and Clear command feature
  src/main/java/seedu/address/logic/commands/ClearAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ClearPatientCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListPatientCommand.java
  src/main/java/seedu/address/logic/parser/UserInputParser.java
  src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/UserInputParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task

#56 fix bug in edit appointment command
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/model/AppointmentSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/NonConflictingAppointmentList.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
Labels: type.BugFix

#66 Add assertions
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/appointment/Timeslot.java
Labels: type.Task

#69 update version number, correct app name in logger
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#78 feat: force delete of appointments in delete doctor command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/doctor/ClearDoctorCommand.java
  src/main/java/seedu/address/logic/commands/doctor/DeleteDoctorCommand.java
  src/main/java/seedu/address/logic/commands/patient/ClearPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/doctor/DeleteDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/DeletePatientCommandParser.java
  src/main/java/seedu/address/model/AppointmentSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/NonConflictingAppointmentList.java
  src/test/java/seedu/address/logic/commands/doctor/ClearDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/doctor/DeleteDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/ClearPatientCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: type.BugFix

#68 Edit command bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/doctor/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/doctor/DeleteDoctorCommand.java
  src/main/java/seedu/address/logic/commands/doctor/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/patient/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/parser/appointment/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/appointment/FindAppointmentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AppointmentSchedule.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/appointment/AppointmentDisplay.java
  src/main/java/seedu/address/model/appointment/NonConflictingAppointmentList.java
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/model/person/Patient.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedDoctor.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableDoctorRecordsTest/duplicateDoctorRecords.json
  src/test/data/JsonSerializableDoctorRecordsTest/typicalDoctorRecords.json
  src/test/data/JsonSerializablePatientRecordsTest/duplicatePatientRecords.json
  src/test/data/JsonSerializablePatientRecordsTest/typicalPatientRecords.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/doctor/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppObjects.java
Labels: type.BugFix, type.Enhancement, type.Task

#83 update-command-summary
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation
